# Replace XXX with the network's name
'site_name': 'XXX Docs'
'site_url': 'https://XXX/'
'home_url': 'https://XXX/'
'site_dir': '/var/www/XXX-docs-static'
'docs_dir': 'XXX-docs'
'copyright': '© 2023 XXX Foundation. All Rights Reserved.'
# Used for extra javascript files in the `docs` repository
# 'extra_javascript':
#   - 'js/externalLinkModal.js' # Enable if you want a warning when users leave your site
#   - 'https://widget.kapa.ai/kapa-widget.bundle.js' # Enable is project is using Kapa
#   - 'js/initKapaWidget.js' # Enable if project is using Kapa
# Used for custom fonts. If you're using a publicly available font, this is not necessary
# 'extra_css':
#   - '/assets/stylesheets/extra.css'
'theme':
  'name': 'material'
  'custom_dir': 'material-overrides'
  'favicon': '/assets/images/XXX-favicon.png'
  'logo': '/assets/images/XXX-logo.png'
  'logo_dark_mode': '/assets/images/XXX-logo-dark.png' # Only required if using dark and light modes  #'font': # This is for Google Fonts
    #'text': 'XXX' # Add the name of the font. The default is Roboto
    #'code': 'XXX' # This is optional. The default is Roboto Mono
  'features':
    - navigation.footer # Shows previous and next on the footer
    - 'navigation.tabs' # Top-level sections are rendered below the header (can be modified to in-line with CSS)
    - 'navigation.tabs.sticky' # When scrolling, the tabs remain at the top of the page
    - 'navigation.sections' # Render top-level sections as groups in the sidebar
    - 'navigation.indexes'
    - 'content.code.copy'
  # Used for light and dark mode feature
  'palette':
    # Palette toggle for light mode
    - 'media': "(prefers-color-scheme: light)"
      'scheme': default
      'toggle':
        'icon': material/weather-night
        'name': Switch to dark mode
    # Palette toggle for dark mode
    - 'media': "(prefers-color-scheme: dark)"
      'scheme': slate
      'toggle':
        'icon': material/weather-sunny
        'name': Switch to light mode
'markdown_extensions':
  - 'codehilite'
  - 'meta' 
  - 'toc':
      'permalink': !!bool 'true'
      'title': 'Sections'
  - 'admonition'
  - 'pymdownx.snippets':
      'base_path': 'XXX-docs/.snippets'
  - 'pymdownx.tabbed':
      'alternate_style': !!bool 'true'
  - 'pymdownx.superfences'
  - 'pymdownx.details'
  - 'attr_list'
'plugins':
  - 'search'
  - 'awesome-pages'
  - 'git-revision-date-localized':
      'enabled': !ENV [ENABLED_GIT_REVISION_DATE, True]
      'enable_creation_date': !!bool 'true'
  - 'redirects':
      'redirect_maps':
        # Redirects will go here as pages get moved around in the following format:
        # 'old-page.md': 'new-page.md'
  - 'macros':
      'include_yaml':
        - 'XXX-docs/variables.yml'
'extra':
  'generator': !!bool 'false'
  'social':
    - 'icon': 'fontawesome/brands/discord'
      'link': 'https://discord.gg/XXX'
      'name': 'Discord'
    - 'icon': 'fontawesome/brands/telegram'
      'link': 'https://t.me/XXX'
      'name': 'Telegram'
    - 'icon': 'fontawesome/brands/twitter'
      'link': 'https://twitter.com/XXX'
      'name': 'Twitter'
    - 'icon': 'fontawesome/brands/github'
      'link': 'https://github.com/XXX'
      'name': 'GitHub'
  'analytics':
    'provider': 'google'
    'property': 'G-XXX'
    'feedback':
      'title': 'Was this page helpful?'
      'ratings':
        - 'icon': 'material/emoticon-happy-outline'
          'name': 'This page was helpful'
          'data': 1
          'note': >-
            Thanks for your feedback!
        - 'icon': 'material/emoticon-sad-outline'
          'name': 'This page could be improved'
          'data': 0
          'note': >-
            Thanks for your feedback! Help us improve this page by submitting
            <a href="https://github.com/XXX/XXX/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">additional feedback</a>.
